name: FPGA Tests

on:
  push:
    branches: [ master, ci-fix ]
  pull_request:
    branches: [ master, ci-fix ]

jobs:
  test-fpga:
    if: ${{ !contains(github.event.pull_request.labels.*.name, 'no-ci') }}
    runs-on: [self-hosted, linux, intel-fpga, xilinx-fpga]
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'recursive'
    - name: Install dependencies
      run: |
        rm -f ~/.dace.conf
        rm -rf .dacecache tests/.dacecache
        . /opt/setupenv
        python -m pip install --upgrade pip
        pip install pytest-xdist flake8 coverage
        pip uninstall -y dace
        pip install -e ".[testing]"
        curl -Os https://uploader.codecov.io/latest/linux/codecov
        chmod +x codecov

    - name: Run FPGA Tests
      run: |
        export COVERAGE_RCFILE=`pwd`/.coveragerc
        # Due to an internal bug in the Xilinx tools, where the current datetime is passed as an integer
        # and overflowed in the year 2022, run the FPGA tests pretending like it's January 1st 2021.
        faketime -f "@2021-01-01 00:00:00" pytest -n auto --cov-report=xml --cov=dace --tb=short -m "fpga"
        coverage report
        coverage xml
        reachable=0
        ping -W 2 -c 1 codecov.io || reachable=$?
        if [ $reachable -eq 0 ]; then
          ./codecov
        else
          echo "Codecov.io is unreachable"
        fi
        killall -9 xsim xsimk || true
